# Включить поддержку Python и загрузить библиотеку DesignScript
import clr
clr.AddReference('ProtoGeometry')
from Autodesk.DesignScript.Geometry import *

# Введенные в этом узле данные сохраняется в виде списка в переменных IN.
elms = IN[0]     # массив элементов
rep = IN[1]      # массив элементов повторений
out = []         # выходной массив
# Разместите код под этой строкой

for el in elms:             # Перебираем элементы массива
	out.append(el)          # Добавляем элемент в результирующий массив
	for r in rep:			# Перебираем повторы
		if (el == r):       # Если элемент равен повтору, то добавляем элемент в результирующий массив еще раз
			out.append(el)  # Добавляем повторно элемент в результирующий массив
		else:               # В противном случае пропускаем элемент
			continue
			
# Назначьте вывод переменной OUT.

OUT = out    # Выводим результирующий массив